// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Runtime.InteropServices;
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.SimulationFrame;
    using Coherence.Entities;
    using Coherence.Utils;
    using Coherence.Brook;
    using Coherence.Core;
    using Logger = Coherence.Log.Logger;
    using UnityEngine;
    using Coherence.Toolkit;
    public struct _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005 : ICoherenceComponentData
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public Quaternion rotation;
            [FieldOffset(16)]
            public Vector3 position;
        }

        public void ResetFrame(AbsoluteSimulationFrame frame)
        {
            FieldsMask |= _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.rotationMask;
            rotationSimulationFrame = frame;
            FieldsMask |= _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.positionMask;
            positionSimulationFrame = frame;
        }

        public static unsafe _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005 FromInterop(IntPtr data, Int32 dataSize, InteropAbsoluteSimulationFrame* simFrames, Int32 simFramesCount)
        {
            if (dataSize != 28) {
                throw new Exception($"Given data size is not equal to the struct size. ({dataSize} != 28) " +
                    "for component with ID 20");
            }

            if (simFramesCount != 2) {
                throw new Exception($"Given simFrames size is not equal to the expected length. ({simFramesCount} != 2) " +
                    "for component with ID 20");
            }

            var orig = new _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005();

            var comp = (Interop*)data;

            orig.rotation = comp->rotation;
            orig.rotationSimulationFrame = simFrames[0].Into();
            orig.position = comp->position;
            orig.positionSimulationFrame = simFrames[1].Into();

            return orig;
        }


        public static uint rotationMask => 0b00000000000000000000000000000001;
        public AbsoluteSimulationFrame rotationSimulationFrame;
        public Quaternion rotation;
        public static uint positionMask => 0b00000000000000000000000000000010;
        public AbsoluteSimulationFrame positionSimulationFrame;
        public Vector3 position;

        public uint FieldsMask { get; set; }
        public uint StoppedMask { get; set; }
        public uint GetComponentType() => 20;
        public int PriorityLevel() => 100;
        public const int order = 0;
        public uint InitialFieldsMask() => 0b00000000000000000000000000000011;
        public bool HasFields() => true;
        public bool HasRefFields() => false;

        private long[] simulationFrames;

        public long[] GetSimulationFrames() {
            if (simulationFrames == null)
            {
                simulationFrames = new long[2];
            }

            simulationFrames[0] = rotationSimulationFrame;
            simulationFrames[1] = positionSimulationFrame;

            return simulationFrames;
        }

        public int GetFieldCount() => 2;


        
        public HashSet<Entity> GetEntityRefs()
        {
            return default;
        }

        public uint ReplaceReferences(Entity fromEntity, Entity toEntity)
        {
            return 0;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper)
        {
            return IEntityMapper.Error.None;
        }

        public ICoherenceComponentData Clone() => this;
        public int GetComponentOrder() => order;
        public bool IsSendOrdered() => false;


        public AbsoluteSimulationFrame? GetMinSimulationFrame()
        {
            AbsoluteSimulationFrame? min = null;

            if ((FieldsMask & _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.rotationMask) != 0 && (min == null || this.rotationSimulationFrame < min))
            {
                min = this.rotationSimulationFrame;
            }
            if ((FieldsMask & _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.positionMask) != 0 && (min == null || this.positionSimulationFrame < min))
            {
                min = this.positionSimulationFrame;
            }

            return min;
        }

        public ICoherenceComponentData MergeWith(ICoherenceComponentData data)
        {
            var other = (_5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005)data;
            var otherMask = other.FieldsMask;

            FieldsMask |= otherMask;
            StoppedMask &= ~(otherMask);

            if ((otherMask & 0x01) != 0)
            {
                this.rotationSimulationFrame = other.rotationSimulationFrame;
                this.rotation = other.rotation;
            }

            otherMask >>= 1;
            if ((otherMask & 0x01) != 0)
            {
                this.positionSimulationFrame = other.positionSimulationFrame;
                this.position = other.position;
            }

            otherMask >>= 1;
            StoppedMask |= other.StoppedMask;

            return this;
        }

        public uint DiffWith(ICoherenceComponentData data)
        {
            throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");
        }

        public static uint Serialize(_5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005 data, bool isRefSimFrameValid, AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream bitStream, Logger logger)
        {
            if (bitStream.WriteMask(data.StoppedMask != 0))
            {
                bitStream.WriteMaskBits(data.StoppedMask, 2);
            }

            var mask = data.FieldsMask;

            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.rotationSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }
                var fieldValue = (data.rotation.ToCoreQuaternion());
                bitStream.WriteQuaternion(fieldValue, 32);
            }
            mask >>= 1;
            if (bitStream.WriteMask((mask & 0x01) != 0))
            {
                if (isRefSimFrameValid) {
                    var simFrameDelta = data.positionSimulationFrame - referenceSimulationFrame;
                    if (simFrameDelta > byte.MaxValue) {
                        simFrameDelta = byte.MaxValue;
                    }

                    SerializeTools.WriteFieldSimFrameDelta(bitStream, (byte)simFrameDelta);
                } else {
                    SerializeTools.WriteFieldSimFrameDelta(bitStream, 0);
                }
                var fieldValue = (data.position.ToCoreVector3());
                bitStream.WriteVector3(fieldValue, FloatMeta.NoCompression());
            }
            mask >>= 1;

            return mask;
        }

        public static _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005 Deserialize(AbsoluteSimulationFrame referenceSimulationFrame, InProtocolBitStream bitStream)
        {
            var stoppedMask = (uint)0;
            if (bitStream.ReadMask())
            {
                stoppedMask = bitStream.ReadMaskBits(2);
            }

            var val = new _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005();
            if (bitStream.ReadMask())
            {
                val.rotationSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.rotation = bitStream.ReadQuaternion(32).ToUnityQuaternion();
                val.FieldsMask |= _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.rotationMask;
            }
            if (bitStream.ReadMask())
            {
                val.positionSimulationFrame = referenceSimulationFrame + DeserializerTools.ReadFieldSimFrameDelta(bitStream);

                val.position = bitStream.ReadVector3(FloatMeta.NoCompression()).ToUnityVector3();
                val.FieldsMask |= _5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005.positionMask;
            }

            val.StoppedMask = stoppedMask;

            return val;
        }


        public override string ToString()
        {
            return $"_5e0c0b0b1e0d32b40bf8ad9c0e90a191_2630557354540798005(" +
                $" rotation: { this.rotation }" +
                $", rotationSimFrame: { this.rotationSimulationFrame }" +
                $" position: { this.position }" +
                $", positionSimFrame: { this.positionSimulationFrame }" +
                $" Mask: { System.Convert.ToString(FieldsMask, 2).PadLeft(2, '0') }, " +
                $"Stopped: { System.Convert.ToString(StoppedMask, 2).PadLeft(2, '0') })";
        }
    }

}
