// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f429c4d79d752e4b871ff4ac54d7195_908f2bf63c6047f5827e6db3c40d6088 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve]
    public class Binding_0f429c4d79d752e4b871ff4ac54d7195_3cf01491ad0a4179b4a9028f09706e39 : BoolBinding
    {   
        private global::GlobalNotification CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::GlobalNotification)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107);
        public override string CoherenceComponentName => "_0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.enabled); }
            set { CastedUnityComponent.enabled = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107)coherenceComponent).enabled;

            var simFrame = ((_0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107)coherenceComponent).enabledSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.enabled = Value;
            }
            else
            {
                update.enabled = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.enabledSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _0f429c4d79d752e4b871ff4ac54d7195_6406197125838560107();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_0f429c4d79d752e4b871ff4ac54d7195 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_0f429c4d79d752e4b871ff4ac54d7195>();
        
        private global::GlobalNotification _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f_CommandTarget;
        private global::GlobalNotification _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["908f2bf63c6047f5827e6db3c40d6088"] = new Binding_0f429c4d79d752e4b871ff4ac54d7195_908f2bf63c6047f5827e6db3c40d6088(),
			["3cf01491ad0a4179b4a9028f09706e39"] = new Binding_0f429c4d79d752e4b871ff4ac54d7195_3cf01491ad0a4179b4a9028f09706e39(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_0f429c4d79d752e4b871ff4ac54d7195()
        {
            bakedCommandBindings.Add("bacae035c0a74634ab33380502abaf8f", BakeCommandBinding__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f);
            bakedCommandBindings.Add("1c72a3c3f7e747e8b4df0063055415ec", BakeCommandBinding__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f_CommandTarget = (global::GlobalNotification)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"GlobalNotification.ReceiveChatMessage",
            	"(System.String)",
            	SendCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f,
            	ReceiveLocalCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f,
            	MessageTarget.All,
            	_0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(command);
        }

        private void ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(_0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f command)
        {
            var target = _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f_CommandTarget;
			target.ReceiveChatMessage((System.String)(command.message));
        }
        private void BakeCommandBinding__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec_CommandTarget = (global::GlobalNotification)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"GlobalNotification.RequestBroadcastChatMessage",
            	"(System.String)",
            	SendCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec,
            	ReceiveLocalCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec,
            	MessageTarget.All,
            	_0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(GenericCommandRequestArgs requestArgs)
        {
            var command = new _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(command);
        }

        private void ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(_0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec command)
        {
            var target = _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec_CommandTarget;
			target.RequestBroadcastChatMessage((System.String)(command.message));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f castedCommand:
                    ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_bacae035c0a74634ab33380502abaf8f(castedCommand);
                    break;
                case _0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec castedCommand:
                    ReceiveCommand__0f429c4d79d752e4b871ff4ac54d7195_1c72a3c3f7e747e8b4df0063055415ec(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_0f429c4d79d752e4b871ff4ac54d7195 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_0f429c4d79d752e4b871ff4ac54d7195>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
